### ISSUE TITLE
sortir un listing niveau par niveau

### ISSUE THREAD

**Issue by Lucpradier** [gruelt/laragym#13]
Du style (soit excel pour le pointage futur en format papier soit pdf (1 page par groupe) pour une visu du remplissage des groupes (au lieu de le faire à la main comme à commencer Marion ;-) )

N8 : 
1- Pradier Annabelle
2- Devigne Marilou 
.....

Adulte agrés : 
1- Gruel Thomas
2- Breuil Stéphanie 
3- .....

**Comment by gruelt** [comment]
http://my.fjepgym.fr/equipes/9

comme ça , mais en version à imprimer ? ou juste ouvri à marion les accés ?

**Comment by Lucpradier** [comment]
En version à imprimer

**Comment by gruelt** [comment]
Ok, une page par groupe avec photo, pourra servir de pointage papier
+penser à ajouter cases vides pour gyms ajoutés
