### ISSUE TITLE
lien entre écrans

### ISSUE THREAD

**Issue by Lucpradier** [gruelt/laragym#18]
a partir de la fiche d'un gymnaste, lien pour voir la fiche du responsable

**Comment by gruelt** [comment]
Si on parle de la même chose , c'est déjà en place.
![Capture du 2019-07-11 11-33-28](https://user-images.githubusercontent.com/5389596/61040001-15749e00-a3d0-11e9-9ee1-115cbeca92f7.png)

**Comment by Lucpradier** [comment]
C'était bien ça, il était pas assez gros ce bouton , pourtant je regardait bien à cet endroit !!!!!
